services:
  api:
    environment:
      - APP_ENV=production
      - DEBUG=false
      - LOG_LEVEL=INFO
      - API_RELOAD=false
      - API_WORKERS=4
      - HTTPS_ONLY=true
      - SESSION_COOKIE_SECURE=true
    # AWS: 필요 시 이미지 태그/리소스 제한/로깅 추가
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - files-data:${FILES_BASE_DIR:-/app/files}   # ✅ 기본값 /app/files
      - secrets-data:/app/secrets
      - logs-data:/app/logs

  redis:
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

  nginx:
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

volumes:
  logs-data:
