// Mocks generated by Mockito 5.4.6 from annotations
// in user_app/test/features/voice/ui/voice_interface_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:flutter_tts/flutter_tts.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:user_app/features/auth/models/auth_models.dart' as _i2;
import 'package:user_app/features/auth/state/auth_provider.dart' as _i8;
import 'package:user_app/features/notification/models/notification_models.dart'
    as _i5;
import 'package:user_app/features/notification/state/notification_provider.dart'
    as _i4;
import 'package:user_app/features/voice/service/flutter_tts_service.dart'
    as _i10;
import 'package:user_app/features/voice/service/openai_service.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeAuthState_0 extends _i1.SmartFake implements _i2.AuthState {
  _FakeAuthState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFlutterTts_1 extends _i1.SmartFake implements _i3.FlutterTts {
  _FakeFlutterTts_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationProvider extends _i1.Mock
    implements _i4.NotificationProvider {
  MockNotificationProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isConnected =>
      (super.noSuchMethod(Invocation.getter(#isConnected), returnValue: false)
          as bool);

  @override
  List<_i5.NotificationMessage> get messages =>
      (super.noSuchMethod(
            Invocation.getter(#messages),
            returnValue: <_i5.NotificationMessage>[],
          )
          as List<_i5.NotificationMessage>);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  int get unreadCount =>
      (super.noSuchMethod(Invocation.getter(#unreadCount), returnValue: 0)
          as int);

  @override
  List<_i5.NotificationMessage> get unreadMessages =>
      (super.noSuchMethod(
            Invocation.getter(#unreadMessages),
            returnValue: <_i5.NotificationMessage>[],
          )
          as List<_i5.NotificationMessage>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<bool> connect(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#connect, [userId]),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  _i6.Future<void> disconnect() =>
      (super.noSuchMethod(
            Invocation.method(#disconnect, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<bool> sendNotification({
    required List<String>? recipients,
    required String? title,
    required String? body,
    _i5.NotificationKind? kind = _i5.NotificationKind.info,
    _i5.NotificationSeverity? severity = _i5.NotificationSeverity.blue,
    String? channel = 'websocket',
    Map<String, dynamic>? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendNotification, [], {
              #recipients: recipients,
              #title: title,
              #body: body,
              #kind: kind,
              #severity: severity,
              #channel: channel,
              #metadata: metadata,
            }),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void markAsRead(String? messageId) => super.noSuchMethod(
    Invocation.method(#markAsRead, [messageId]),
    returnValueForMissingStub: null,
  );

  @override
  void markAllAsRead() => super.noSuchMethod(
    Invocation.method(#markAllAsRead, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeMessage(String? messageId) => super.noSuchMethod(
    Invocation.method(#removeMessage, [messageId]),
    returnValueForMissingStub: null,
  );

  @override
  void clearMessages() => super.noSuchMethod(
    Invocation.method(#clearMessages, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthProvider extends _i1.Mock implements _i8.AuthProvider {
  MockAuthProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.AuthState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeAuthState_0(this, Invocation.getter(#state)),
          )
          as _i2.AuthState);

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get isLoading =>
      (super.noSuchMethod(Invocation.getter(#isLoading), returnValue: false)
          as bool);

  @override
  String get userId =>
      (super.noSuchMethod(
            Invocation.getter(#userId),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#userId),
            ),
          )
          as String);

  @override
  String get userName =>
      (super.noSuchMethod(
            Invocation.getter(#userName),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#userName),
            ),
          )
          as String);

  @override
  String get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as String);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> login({
    required String? password,
    required bool? rememberMe,
    required bool? autoLogin,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#login, [], {
              #password: password,
              #rememberMe: rememberMe,
              #autoLogin: autoLogin,
            }),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FlutterTtsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterTtsService extends _i1.Mock implements _i10.FlutterTtsService {
  MockFlutterTtsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FlutterTts get flutterTts =>
      (super.noSuchMethod(
            Invocation.getter(#flutterTts),
            returnValue: _FakeFlutterTts_1(
              this,
              Invocation.getter(#flutterTts),
            ),
          )
          as _i3.FlutterTts);

  @override
  set flutterTts(_i3.FlutterTts? value) => super.noSuchMethod(
    Invocation.setter(#flutterTts, value),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<bool> isInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#isInitialized, []),
            returnValue: _i6.Future<bool>.value(false),
          )
          as _i6.Future<bool>);

  @override
  void setCallbacks({
    dynamic Function()? onComplete,
    dynamic Function()? onError,
  }) => super.noSuchMethod(
    Invocation.method(#setCallbacks, [], {
      #onComplete: onComplete,
      #onError: onError,
    }),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> stop() =>
      (super.noSuchMethod(
            Invocation.method(#stop, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> pause() =>
      (super.noSuchMethod(
            Invocation.method(#pause, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<String>> getAvailableVoices() =>
      (super.noSuchMethod(
            Invocation.method(#getAvailableVoices, []),
            returnValue: _i6.Future<List<String>>.value(<String>[]),
          )
          as _i6.Future<List<String>>);

  @override
  _i6.Future<void> setVoice(String? voiceName) =>
      (super.noSuchMethod(
            Invocation.method(#setVoice, [voiceName]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setSpeechRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeechRate, [rate]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  String getCurrentVoice() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentVoice, []),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getCurrentVoice, []),
            ),
          )
          as String);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OpenAiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenAiService extends _i1.Mock implements _i11.OpenAiService {
  MockOpenAiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<String> chat(String? userText) =>
      (super.noSuchMethod(
            Invocation.method(#chat, [userText]),
            returnValue: _i6.Future<String>.value(
              _i9.dummyValue<String>(
                this,
                Invocation.method(#chat, [userText]),
              ),
            ),
          )
          as _i6.Future<String>);
}
